{% set name = "bootstrap" %}
{% set version = "4.1.1" %}
{% set sha256 = "cedf2e0c3f46625276457e68ab70fce633c185a811390450e2bb425ae73c2b38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/twbs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
    
test:
  commands:
    - npm list -g bootstrap
  requires:
    - nodejs
   

about:
  home: https://github.com/twbs/bootstrap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile first projects on the web.'
  description: |
    Sleek, intuitive, and powerful front-end framework for faster and easier web development.  
  doc_url: https://bootstrapdocs.com/
  dev_url: https://github.com/twbs/bootstrap

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
