{% set name = "bootstrap" %}
{% set version = "4.5.2" %}
{% set sha256 = "9855c7bfc2a3a2de9120fa4112aa922a98a7df810791c2415d13aefd8c89d8f8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/twbs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs


test:
  commands:
    - npm list -g bootstrap
  requires:
    - nodejs


about:
  home: https://github.com/twbs/bootstrap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile first projects on the web.
  description: |
    Sleek, intuitive, and powerful front-end framework for faster and easier web development.  
  doc_url: https://bootstrapdocs.com/
  dev_url: https://github.com/twbs/bootstrap

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
