travis:
  secure:
    BINSTAR_TOKEN: ORintTlgl2PgFtd0jBi6WLsOw8ZGj1VAgLXiYZSlo8RiF5A207UoRR5Daz2M0DIHX7RLwMPwS255DhQO1/Pwpndz8NXW9iepxMYWYjdwBGJDULq/YHsY/+E4YwM00GfyMfLUwyP3WRkYkFuHUbqY0DKBYI9AY+yYUl7kUo10rcPU+rNqxUQDDCT7Ejp0OpI4fLnbF47OlHMyASs/ovIBQ7d/qSWk229zMumFaZg7Hl36g/LCG2Wz4N4RMWh5Q2yxM8fQ+GTEtbPWBwHK83gJPuK4a9MzIRAPK1Rw7aJOgJ56GUJx8nrdYKN+QbT0yrgk+ZBNau8+au7LTx26T9cBtyYDsaLApjNdmGTteKfkAobVZ6zqouLUV3ukn4wakiDyiKqQ0aUy6fn6rQbFKA/iUEn4cRX7SeUezutT4dCcMrDz41/mjVxxfZ9t/1S8MJFIeAGvHBlE85NMaGx5GFw71M2KOfdat2hBROdOs31wcFk9EQYXC88NE3oLIC19zaywxEDS0okRm96QB6BB6OJo0HZLzTpDvonfoAppCfyIEMT2kqo1fNJivdNIA4jAVv0kReTz/FmHZJE6EU8i2SO11BKuWLUOCCkRG6lOzFEHGYNfl4rfwobyO7V27JlQ+Eb0idL/V0EwBuNg8ZUU6dhu3CkW+gieoyqapMnlO+sKz6Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
