travis:
  secure:
    BINSTAR_TOKEN: H01FW56JIQFIeAV3Ww015EB0ftp3tZ7UTj+8oOundKX7lBE0FpHe9/tx1fTXleWRch3gSuyf8pCwk7Y6CtnX12Ep1xF+4Id1/U0DMxGUNt31W8M4e9E3tD0lgs3Gfj8pTTbuIEQyJmRR+SWfc6m0qgVUytaypiGUy+Kr5YtCavilPnLjupy0fCST5vBDHJSnDOpFvuLYk6azZoLZhMRIkT0O0ImQRpRSMf62gByCRfJS1V8U45c0M/368R10UKXr5pAXeNNXp3oKacedtPMIh5UNNfioE7QLHlFAIYazV2gr93V4qiA0RHXNFoe8MlLu6Q4ehr7MkR4D42pMLxj9SV/MUqvBWcdhm6iR36+bOzsZKMlWJUIoXbgLRKriUTwzsfehKDgeyXqVTNVGM56impaCGWMLXAVqek/wtMRY0VnCxxnFE5x9hCziKtQpLghSUxTnmhuW5jtuNzWXGf8qqdMF2IkTopPvyj2veoEUlxATZD3ADeA52iVEJUrk2c/IuDw7zuhdSgOEvBk/S9q9SZMGAvWT5+rKJe//QV/k7VkFC0xn0iMbFIShL5Ln1hH8q2AL6an8vZOncu9r7Q5XwzsS7T4Jjiv/Nd0xCDofEkIdMhMoL6chrSFQMZFK1zzjgR5RJIahLI6JAQjiUIWSbhKX/z58Y+/gTAX3OEC1mm4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
